config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'

  resources :tweets do
    resources :comments
  end

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  MINIMUM_TITLE_LENGTH = 5
  MAKSIMUM_BODY_LENGTH = 140

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: MINIMUM_TITLE_LENGTH }
  validates :body, presence: true, length: { maximum: MAKSIMUM_BODY_LENGTH }
end

app/models/user.rb
class User < ApplicationRecord
  MAXIMUM_NAME_LENGTH = 255
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH =5
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_secure_password

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }
  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:danger] = 'Please sign in to continue.'
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    @tweet = @comment.tweet
  end

  def update
    @tweet = @comment.tweet

    if @comment.update(comment_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    tweet = @comment.tweet

    if equal_with_current_user?(tweet.user)
      @comment.destroy
      redirect_to tweet
    else
      flash[:danger] = 'Wrong User'
      redirect_to(root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def correct_user
    unless equal_with_current_user?(@comment.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Welcome #{user.name} !"
      redirect_to user
    else
      flash.now[:danger] = 'Email and password miss match'
      render :new
    end

  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :find_tweet, except: [:index, :new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show

  end

  def new

    @tweet = Tweet.new
  end

  def create

    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body)
  end

  def find_tweet
    @tweet = Tweet.find(params[:id])
  end

  def correct_user
    unless equal_with_current_user?(@tweet.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="column is-6 is-offset-3">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
           <strong><%= comment.user.name %></strong> <small><%= time_ago_in_words(comment.created_at) %> ago </small>
          <br>
          <%= comment.body %>
        </p>
      </div>
      <nav class="level is-mobile">
          <% if equal_with_current_user?(comment.user) %>
          <div class="level-left">
            <%= link_to edit_tweet_comment_path(comment.tweet, comment), class: "level-item" do %>
              <span class="icon is-small"><i class="fas fa-edit"></i></span>
            <% end %>
            <%= link_to tweet_comment_path(comment.tweet, comment), method: :delete , class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
              <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
           <% elsif equal_with_current_user?(comment.tweet.user) %>
          <div class="level-left">
            <%= link_to tweet_comment_path(comment.tweet, comment), method: :delete , class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
              <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= heading %></h1>
      </div>
    </div>

    <% if comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</p>
            <br>
            <p>
            <% comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [tweet, comment], local: true do |form| %>
            
            <div class="field">
              <p class="control">
                  <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit "Save", class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", tweet_path(tweet), class: 'button is-light' %>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form',
  tweet: @tweet,
  comment: @comment,
  heading: "Edit #{@tweet.title}'s comment",
  submit: "Update" %>

app/views/comments/new.html.erb
<%= render 'form',
  tweet: @tweet,
  comment: @comment,
  heading: "#{@tweet.title} - New Comment",
  submit: "Save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>

  <body>
    <section class="section">
      <%= render 'shared/nav_bar' %>
        <%= render 'shared/flash' %>
        
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>

    <div class="column is-8 is-offset-2">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>

    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notificaton is-primart global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-dark">
      <div class="fab fa-twitter icon is-large"></div>
      <div class="navbar-brand"></div>
      <%= link_to root_path, class: "navbar-item" do %>
        <div class="title is-5 button is-info">Twitter</div>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
      </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
        <div class="field is-grouped">
           <p class="control">
            <% if logged_in? %>
            <%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-rounded" %>
            <%= link_to "Log Out", logout_path, method: :delete, class: "button is-danger is-rounded" %>
            <% else %>
              <%= link_to "Log In", login_path, class: "button is-link is-inverted is-rounded" %>
              <%= link_to "Sign Up", users_signup_path, class: "button is-link is-rounded" %>
            <% end %>
           </p>
        </div>
      </div>
    </div>
  </nav>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= heading %></h1>
      </div>
    </div>

    <% if tweet.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</p>
            <br>
            <p>
            <% tweet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <%= form_with model: tweet, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: "Title" %>
          </div>
        </div>


        <div class="field">
          <%= form.label :body, class: "label" %>

          <div class="control">
            <%= form.text_area :body, class: "textarea", placeholder: 'Your body' %>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit submit, class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", cancel_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="column is-6 is-offset-3">
  <div class="card">
    <% unless local_assigns[:show] %>
      <header class="card-header">
          <p class="card-header-title">
            <%= tweet.title %>
          </p>
      </header>
    <% end %>
    <div class="card-content">
      <div class="content">
        <p><%= tweet.body %></p>
      </div>
    </div>
    <footer class="card-footer">
      <% if local_assigns[:show] %>
        <%= link_to "Back", root_path, class: "card-footer-item" %>
      <% else %>
        <%= link_to "Show", tweet_path(tweet), class: "card-footer-item" %>
      <% end %>
       <% if logged_in? && equal_with_current_user?(tweet.user) %>
        <%= link_to "Edit", edit_tweet_path(tweet), class: "card-footer-item" %>
      <% end %>

       <% if local_assigns[:show] && logged_in? %>
        <%= link_to "New Comment", new_tweet_comment_path(tweet), class: "card-footer-item" %>
      <% end %>

      <% if logged_in? && equal_with_current_user?(tweet.user) %>
        <%= link_to "Delete", tweet_path(tweet), method: :delete,
            data: { confirm: "Are you sure you want to delete this tweet?" },
            class: "card-footer-item" %>
      <% end %>
    </footer>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'form',
  tweet: @tweet,
  submit: 'Update Tweet',
  cancel_path: tweet_path(@tweet),
  heading: 'Edit Tweet' %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>Tweets</h1>
      </div>
    </div>

    <%= render @tweets %>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'form',
  tweet: @tweet,
  submit: 'Save Tweet',
  cancel_path: root_path,
  heading: 'New Tweet' %>

app/views/tweets/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @tweet.title %></h1>
      </div>
    </div>

    <%= render @tweet, show: true %>

     <%= render @tweet.comments %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>New User</h1>
      </div>
    </div>

    <% if @user.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>
            <br>
            <p>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: "label" %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name"%>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: "label" %>

          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>

          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'Your password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>

          <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder: 'Confirm password' %>
          </div>
        </div>


        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", tweets_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h3><%= @user.name %></h3>
        <p><%= @user.email %></p>
      </div>
    </div>
  </div>
</div>